from __future__ import annotations
import logging
from dataclasses import dataclass, field
from typing import List, Literal

_logger = logging.getLogger(__name__)

ArtifactFormat = Literal["bash", "powershell", "ansible", "reg", "gpo"]


@dataclass
class Artifact:
    format: str
    content: str
    rule_count: int
    os_target: str
    warnings: List[str] = field(default_factory=list)


class ArtifactGenerator:
    """
    Generates hardening artifacts in multiple formats from CIS YAML rule data.

    Formats:
      bash       — Linux shell script (uses remediation_script_content)
      powershell — Windows PowerShell script
      ansible    — Ansible playbook YAML (uses remediation_command / script)
      reg        — Windows Registry export (.reg) stub
      gpo        — Group Policy summary (human-readable text)
    """

    def generate(
        self,
        rules: List[dict],
        fmt: ArtifactFormat,
        os_target: str = "ubuntu_24_04",
        security_level: str = "balanced",
    ) -> Artifact:
        dispatch = {
            "bash": self._bash,
            "powershell": self._powershell,
            "ansible": self._ansible,
            "reg": self._reg,
            "gpo": self._gpo,
        }
        fn = dispatch.get(fmt)
        if fn is None:
            raise ValueError(f"Unsupported artifact format: {fmt!r}")
        return fn(rules, os_target, security_level)

    # ── format generators ────────────────────────────────────────────────────

    def _bash(self, rules: List[dict], os_target: str, security_level: str) -> Artifact:
        lines = [
            "#!/usr/bin/env bash",
            f"# CIS Hardening Script — {os_target}",
            f"# Security Level: {security_level}",
            "# Generated by AI-Powered OS Hardening",
            "set -euo pipefail",
            "",
        ]
        warnings: List[str] = []
        count = 0
        for rule in rules:
            rid = rule.get("id", "?")
            title = rule.get("title", "")
            script = rule.get("remediation_script_content") or rule.get("remediation_command", "")
            if not script:
                warnings.append(f"Rule {rid}: no remediation script — skipped")
                continue
            lines += [f"# ── Rule {rid}: {title} ──", script.strip(), ""]
            count += 1
        return Artifact(
            format="bash", content="\n".join(lines),
            rule_count=count, os_target=os_target, warnings=warnings,
        )

    def _powershell(self, rules: List[dict], os_target: str, security_level: str) -> Artifact:
        lines = [
            "#Requires -RunAsAdministrator",
            f"# CIS Hardening Script — {os_target}",
            f"# Security Level: {security_level}",
            "# Generated by AI-Powered OS Hardening",
            "",
        ]
        warnings: List[str] = []
        count = 0
        for rule in rules:
            rid = rule.get("id", "?")
            title = rule.get("title", "")
            script = rule.get("remediation_script_content") or rule.get("remediation_command", "")
            lines.append(f"# Rule {rid}: {title}")
            if script:
                lines += [script.strip(), ""]
                count += 1
            else:
                lines += ["# TODO: Manual configuration required — see CIS Benchmark", ""]
                warnings.append(f"Rule {rid}: no script — manual review needed")
        return Artifact(
            format="powershell", content="\n".join(lines),
            rule_count=count, os_target=os_target, warnings=warnings,
        )

    def _ansible(self, rules: List[dict], os_target: str, security_level: str) -> Artifact:
        tasks: List[str] = []
        warnings: List[str] = []
        count = 0
        for rule in rules:
            rid = rule.get("id", "?")
            title = rule.get("title", "")
            script = rule.get("remediation_script_content", "")
            cmd = rule.get("remediation_command", "")
            source = script or cmd
            if source:
                indented = "\n".join(f"        {ln}" for ln in source.strip().splitlines())
                tasks.append(
                    f"    - name: \"CIS {rid} - {title}\"\n"
                    f"      shell: |\n{indented}\n"
                    f"      ignore_errors: yes"
                )
                count += 1
            else:
                warnings.append(f"Rule {rid}: no command — skipped")

        playbook = (
            f"---\n"
            f"- name: CIS Hardening — {os_target}\n"
            f"  hosts: all\n"
            f"  become: yes\n"
            f"  vars:\n"
            f"    security_level: {security_level}\n"
            f"  tasks:\n"
            + "\n\n".join(tasks)
        )
        return Artifact(
            format="ansible", content=playbook,
            rule_count=count, os_target=os_target, warnings=warnings,
        )

    def _reg(self, rules: List[dict], os_target: str, security_level: str) -> Artifact:
        lines = [
            "Windows Registry Editor Version 5.00",
            f"; CIS Hardening — {os_target} | Level: {security_level}",
            "; Generated by AI-Powered OS Hardening",
            "",
        ]
        warnings: List[str] = []
        count = 0
        for rule in rules:
            rid = rule.get("id", "?")
            title = rule.get("title", "")
            reg_path = rule.get("registry_path")
            reg_value = rule.get("registry_value")
            if reg_path and reg_value:
                lines += [f"; Rule {rid}: {title}", f"[{reg_path}]", str(reg_value), ""]
                count += 1
            else:
                warnings.append(f"Rule {rid}: no registry_path/registry_value — skipped")
        if count == 0:
            lines.append("; No registry entries found for selected rules.")
        return Artifact(
            format="reg", content="\n".join(lines),
            rule_count=count, os_target=os_target, warnings=warnings,
        )

    def _gpo(self, rules: List[dict], os_target: str, security_level: str) -> Artifact:
        lines = [
            f"# Group Policy Summary — {os_target}",
            f"# Security Level: {security_level}",
            "# Generated by AI-Powered OS Hardening",
            "",
            "## Policy Settings",
            "",
        ]
        count = 0
        for rule in rules:
            rid = rule.get("id", "?")
            title = rule.get("title", "")
            desc = (rule.get("description") or "")[:300]
            lvl = rule.get("level", "N/A")
            tags = ", ".join(rule.get("tags", [])) or "N/A"
            lines += [
                f"### {rid}: {title}",
                f"- CIS Level  : {lvl}",
                f"- Category   : {rule.get('category', 'N/A')}",
                f"- Tags       : {tags}",
                f"- Description: {desc}",
                "",
            ]
            count += 1
        return Artifact(
            format="gpo", content="\n".join(lines),
            rule_count=count, os_target=os_target, warnings=[],
        )
