from __future__ import annotations
import logging
import re
from dataclasses import dataclass, field
from typing import List, Literal, Tuple

_logger = logging.getLogger(__name__)

ArtifactFormat = Literal["bash", "powershell", "ansible", "reg", "gpo"]


@dataclass
class Artifact:
    format: str
    content: str
    rule_count: int
    os_target: str
    warnings: List[str] = field(default_factory=list)


class ArtifactGenerator:
    """
    Generates hardening artifacts in multiple formats from CIS YAML rule data.

    Formats:
      bash       — Linux shell script (uses remediation_script_content)
      powershell — Windows PowerShell script
      ansible    — Ansible playbook YAML (uses remediation_command / script)
      reg        — Windows Registry export (.reg) stub
      gpo        — Group Policy summary (human-readable text)
    """

    def generate(
        self,
        rules: List[dict],
        fmt: ArtifactFormat,
        os_target: str = "ubuntu_24_04",
        security_level: str = "balanced",
    ) -> Artifact:
        dispatch = {
            "bash": self._bash,
            "powershell": self._powershell,
            "ansible": self._ansible,
            "reg": self._reg,
            "gpo": self._gpo,
        }
        fn = dispatch.get(fmt)
        if fn is None:
            raise ValueError(f"Unsupported artifact format: {fmt!r}")
        return fn(rules, os_target, security_level)

    # ── format generators ────────────────────────────────────────────────────

    # Servis reload/restart satırı (sona TEK sefer taşınır)
    _RELOAD_RE = re.compile(r"^(sudo\s+)?(systemctl\s+(reload|restart)\b|service\s+\S+\s+(reload|restart)\b)")

    @staticmethod
    def _sanitize_remediation(script: str) -> Tuple[str, List[str]]:
        """Ham kural remediation gövdesini BİRLEŞTİRMEYE hazırla (production-grade artifact için):
          • gömülü shebang (`#!/...`) satırlarını SİL — tek dosyada yalnız 1 shebang olmalı.
          • `systemctl/service reload|restart` satırlarını AYIKLA — sona TEK sefer taşınır
            (kural başına 19× reload yerine 1× + config doğrulama).
        Gövdedeki `return` korunur; çağıran her kuralı fonksiyona sarar → `return` geçerli olur.
        Döner: (temizlenmiş_gövde, [reload_komutları]).
        """
        body: List[str] = []
        reloads: List[str] = []
        for ln in script.strip().splitlines():
            s = ln.strip()
            if s.startswith("#!"):
                continue
            if ArtifactGenerator._RELOAD_RE.match(s):
                if s not in reloads:
                    reloads.append(s)
                continue
            body.append(ln)
        while body and not body[0].strip():
            body.pop(0)
        while body and not body[-1].strip():
            body.pop()
        return "\n".join(body), reloads

    def _bash(self, rules: List[dict], os_target: str, security_level: str) -> Artifact:
        header = [
            "#!/usr/bin/env bash",
            f"# CIS Hardening Script — {os_target}",
            f"# Security Level: {security_level}",
            "# Generated by AI-Powered OS Hardening",
            "set -euo pipefail",
            "",
            'TS="$(date +%F-%H%M%S)"',
            'BACKUP_DIR="/var/backups/cis-hardening-${TS}"',
            'log() { printf "[%s] %s\\n" "$(date +%T)" "$*"; }',
            'mkdir -p "$BACKUP_DIR"',
            "",
        ]
        # ── Tek-sefer YEDEK (config_files metadata'sından) — geri dönüş için ──
        backup_files: List[str] = []
        for rule in rules:
            for cf in rule.get("config_files", []) or []:
                if cf and cf not in backup_files:
                    backup_files.append(cf)
        if backup_files:
            header.append("# ── Yedek (değişiklik öncesi) ──")
            for cf in backup_files:
                header.append(f'[ -e "{cf}" ] && cp -a "{cf}" "$BACKUP_DIR/" && log "yedeklendi: {cf}"')
            header.append("")

        bodies: List[str] = []
        reloads: List[str] = []
        warnings: List[str] = []
        count = 0
        for rule in rules:
            rid = rule.get("id", "?")
            title = rule.get("title", "")
            script = rule.get("remediation_script_content") or rule.get("remediation_command", "")
            if not script:
                warnings.append(f"Rule {rid}: no remediation script — skipped")
                continue
            cleaned, rule_reloads = self._sanitize_remediation(script)
            for r in rule_reloads:
                if r not in reloads:
                    reloads.append(r)
            fn = "apply_" + re.sub(r"[^0-9A-Za-z]", "_", str(rid))
            indented = "\n".join(("    " + ln) if ln.strip() else "" for ln in cleaned.splitlines())
            bodies += [
                f"# ── Rule {rid}: {title} ──",
                f"{fn}() {{",
                indented,
                "}",
                # Tek kuralın hatası tüm script'i ABORT etmesin (set -e bypass): uyar, devam et.
                f'{fn} && log "OK  {rid}" || log "UYARI {rid}: uygulanamadı"',
                "",
            ]
            count += 1

        # ── Servis yeniden yükleme: TEK sefer, config DOĞRULAMALI (sshd kilitlenmesini önler) ──
        tail: List[str] = []
        if reloads:
            tail.append("# ── Servis yeniden yükleme (TEK sefer, config doğrulanarak) ──")
            for r in reloads:
                if re.search(r"\bsshd?\b", r):
                    tail.append(
                        f'if sshd -t; then {r}; log "sshd yeniden yüklendi"; '
                        'else log "HATA: sshd config geçersiz — reload atlandı (yedek: $BACKUP_DIR)"; exit 1; fi'
                    )
                else:
                    tail.append(r)
            tail.append("")
        tail.append('log "Tamamlandı. Yedek dizini: $BACKUP_DIR"')

        return Artifact(
            format="bash", content="\n".join(header + bodies + tail),
            rule_count=count, os_target=os_target, warnings=warnings,
        )

    def _powershell(self, rules: List[dict], os_target: str, security_level: str) -> Artifact:
        lines = [
            "#Requires -RunAsAdministrator",
            f"# CIS Hardening Script — {os_target}",
            f"# Security Level: {security_level}",
            "# Generated by AI-Powered OS Hardening",
            "",
        ]
        warnings: List[str] = []
        count = 0
        for rule in rules:
            rid = rule.get("id", "?")
            title = rule.get("title", "")
            script = rule.get("remediation_script_content") or rule.get("remediation_command", "")
            lines.append(f"# Rule {rid}: {title}")
            if script:
                lines += [script.strip(), ""]
                count += 1
            else:
                lines += ["# TODO: Manual configuration required — see CIS Benchmark", ""]
                warnings.append(f"Rule {rid}: no script — manual review needed")
        return Artifact(
            format="powershell", content="\n".join(lines),
            rule_count=count, os_target=os_target, warnings=warnings,
        )

    def _ansible(self, rules: List[dict], os_target: str, security_level: str) -> Artifact:
        tasks: List[str] = []
        warnings: List[str] = []
        count = 0
        for rule in rules:
            rid = rule.get("id", "?")
            title = rule.get("title", "")
            script = rule.get("remediation_script_content", "")
            cmd = rule.get("remediation_command", "")
            source = script or cmd
            if source:
                indented = "\n".join(f"        {ln}" for ln in source.strip().splitlines())
                tasks.append(
                    f"    - name: \"CIS {rid} - {title}\"\n"
                    f"      shell: |\n{indented}\n"
                    f"      ignore_errors: yes"
                )
                count += 1
            else:
                warnings.append(f"Rule {rid}: no command — skipped")

        playbook = (
            f"---\n"
            f"- name: CIS Hardening — {os_target}\n"
            f"  hosts: all\n"
            f"  become: yes\n"
            f"  vars:\n"
            f"    security_level: {security_level}\n"
            f"  tasks:\n"
            + "\n\n".join(tasks)
        )
        return Artifact(
            format="ansible", content=playbook,
            rule_count=count, os_target=os_target, warnings=warnings,
        )

    def _reg(self, rules: List[dict], os_target: str, security_level: str) -> Artifact:
        lines = [
            "Windows Registry Editor Version 5.00",
            f"; CIS Hardening — {os_target} | Level: {security_level}",
            "; Generated by AI-Powered OS Hardening",
            "",
        ]
        warnings: List[str] = []
        count = 0
        for rule in rules:
            rid = rule.get("id", "?")
            title = rule.get("title", "")
            reg_path = rule.get("registry_path")
            reg_value = rule.get("registry_value")
            if reg_path and reg_value:
                lines += [f"; Rule {rid}: {title}", f"[{reg_path}]", str(reg_value), ""]
                count += 1
            else:
                warnings.append(f"Rule {rid}: no registry_path/registry_value — skipped")
        if count == 0:
            lines.append("; No registry entries found for selected rules.")
        return Artifact(
            format="reg", content="\n".join(lines),
            rule_count=count, os_target=os_target, warnings=warnings,
        )

    def _gpo(self, rules: List[dict], os_target: str, security_level: str) -> Artifact:
        lines = [
            f"# Group Policy Summary — {os_target}",
            f"# Security Level: {security_level}",
            "# Generated by AI-Powered OS Hardening",
            "",
            "## Policy Settings",
            "",
        ]
        count = 0
        for rule in rules:
            rid = rule.get("id", "?")
            title = rule.get("title", "")
            desc = (rule.get("description") or "")[:300]
            lvl = rule.get("level", "N/A")
            tags = ", ".join(rule.get("tags", [])) or "N/A"
            lines += [
                f"### {rid}: {title}",
                f"- CIS Level  : {lvl}",
                f"- Category   : {rule.get('category', 'N/A')}",
                f"- Tags       : {tags}",
                f"- Description: {desc}",
                "",
            ]
            count += 1
        return Artifact(
            format="gpo", content="\n".join(lines),
            rule_count=count, os_target=os_target, warnings=[],
        )
