#Requires -Version 5.1
<#
.SYNOPSIS
    GPO Backup Builder for CIS Windows Hardening
.DESCRIPTION
    Generates a complete, portable GPO backup folder structure that can be
    imported using Import-GPO cmdlet in any Active Directory environment.

    Designed for web-application context: no user input required for domain
    info. All domain references use generic placeholders since Import-GPO
    ignores source domain metadata during import.

    Each invocation generates fresh GUIDs to prevent conflicts across
    multiple downloads.
#>

# ---------------------------------------------------------------------------
# Constants — Generic placeholders for XML metadata.
# Import-GPO ignores these during import; they exist only for structural
# validity of the backup format.
# ---------------------------------------------------------------------------
$Script:TEMPLATE_DOMAIN = "HARDENING_TEMPLATE"
$Script:TEMPLATE_DC = "DC.HARDENING_TEMPLATE.LOCAL"
$Script:TEMPLATE_DOMAIN_SID = "S-1-5-21-0-0-0-512"              # Well-known RID 512 = Domain Admins
$Script:TEMPLATE_DOMAIN_GUID = "{00000000-0000-0000-0000-000000000000}"

function New-GPOBackup {
  [CmdletBinding()]
  param(
    [Parameter(Mandatory)]
    [array]$Rules,
        
    [Parameter(Mandatory)]
    [string]$OutputPath,
        
    [Parameter()]
    [string]$GPOName = "CIS Windows Hardening",
        
    [Parameter()]
    [string]$GPODescription = "CIS Benchmark hardening policy generated by CIS Windows Hardening Generator"
  )
    
  # ------------------------------------------------------------------
  # Generate fresh GUIDs for every single run/request.
  # $gpoGuid   = Identifies the GPO itself (source GPO identity)
  # $backupGuid = Identifies this specific backup instance
  # ------------------------------------------------------------------
  $gpoGuid = [guid]::NewGuid().ToString("B").ToUpper()
  $backupGuid = [guid]::NewGuid().ToString("B").ToUpper()
    
  # Create directory structure (mirrors real GPMC backup layout)
  $gpoPath = Join-Path $OutputPath $backupGuid
  $machineScriptsStartup = Join-Path $gpoPath "DomainSysvol\GPO\Machine\Scripts\Startup"
  $machineScriptsShutdown = Join-Path $gpoPath "DomainSysvol\GPO\Machine\Scripts\Shutdown"
  $secEditPath = Join-Path $gpoPath "DomainSysvol\GPO\Machine\microsoft\windows nt\SecEdit"
  $userPath = Join-Path $gpoPath "DomainSysvol\GPO\User"
    
  @($gpoPath, $machineScriptsStartup, $machineScriptsShutdown, $secEditPath, $userPath) | ForEach-Object {
    if (-not (Test-Path $_)) {
      New-Item -Path $_ -ItemType Directory -Force | Out-Null
    }
  }
    
  # ------------------------------------------------------------------
  # Generate GptTmpl.inf (Security Template) — the actual policy payload
  # ------------------------------------------------------------------
  $infContent = New-SecurityTemplateContent -Rules $Rules
  $infPath = Join-Path $secEditPath "GptTmpl.inf"
  $infContent | Set-Content -Path $infPath -Encoding Unicode -Force

  # ------------------------------------------------------------------
  # Generate Registry.pol (Machine) — binary registry policy payload
  # ------------------------------------------------------------------
  $registryRules = $Rules | Where-Object { $null -ne $_.Rule.registry_config }
  if ($registryRules.Count -gt 0) {
    $polPath = Join-Path $gpoPath "DomainSysvol\GPO\Machine\Registry.pol"
    if (Get-Command New-RegistryPol -ErrorAction SilentlyContinue) {
      New-RegistryPol -Rules $registryRules -OutputPath $polPath
    }
    else {
      Write-Warning "New-RegistryPol function not found. Skipping Registry.pol generation."
    }
  }

  # Capture generation timestamp once for consistency across all files
  $generatedAt = Get-Date -Format 'yyyy-MM-ddTHH:mm:ss'
    
  # ------------------------------------------------------------------
  # Generate Backup.xml
  # NOTE: bkp:SourceExpandedPath uses the GPO variable, NOT a local path.
  #       This prevents leaking server filesystem paths into the output.
  # ------------------------------------------------------------------
  $backupXml = @"
<?xml version="1.0" encoding="utf-8"?>
<GroupPolicyBackupScheme bkp:version="2.0" bkp:type="GroupPolicyBackupTemplate" xmlns:bkp="http://www.microsoft.com/GroupPolicy/GPOOperations" xmlns="http://www.microsoft.com/GroupPolicy/GPOOperations">
  <GroupPolicyObject>
    <SecurityGroups>
      <Group bkp:Source="FromDACL">
        <Sid>$($Script:TEMPLATE_DOMAIN_SID)</Sid>
        <SamAccountName>Domain Admins</SamAccountName>
        <Type>Global</Type>
        <Domain>$($Script:TEMPLATE_DOMAIN)</Domain>
      </Group>
    </SecurityGroups>
    <FilePaths/>
    <GroupPolicyCoreSettings>
      <ID>{$gpoGuid}</ID>
      <Domain>$($Script:TEMPLATE_DOMAIN)</Domain>
      <SecurityDescriptor>01 00 04 80</SecurityDescriptor>
      <DisplayName><![CDATA[$GPOName]]></DisplayName>
      <Options>0</Options>
      <UserVersionNumber>0</UserVersionNumber>
      <MachineVersionNumber>1</MachineVersionNumber>
      <MachineExtensionGuids><![CDATA[[{827D319E-6EAC-11D2-A4EA-00C04F79F83A}{803E14A0-B4FB-11D0-A0D0-00A0C90F574B}]]]></MachineExtensionGuids>
      <UserExtensionGuids/>
      <WMIFilter/>
    </GroupPolicyCoreSettings>
    <GroupPolicyExtension bkp:ID="{35378EAC-683F-11D2-A89A-00C04FBBCFA2}" bkp:DescName="Registry">
      <FSObjectFile bkp:Path="%GPO_MACH_FSPATH%\microsoft\windows nt\SecEdit\GptTmpl.inf" bkp:SourceExpandedPath="%GPO_MACH_FSPATH%\microsoft\windows nt\SecEdit\GptTmpl.inf" bkp:Location="DomainSysvol\GPO\Machine\microsoft\windows nt\SecEdit\GptTmpl.inf"/>
    </GroupPolicyExtension>
  </GroupPolicyObject>
</GroupPolicyBackupScheme>
"@
    
  $backupXmlPath = Join-Path $gpoPath "Backup.xml"
  $backupXml | Set-Content -Path $backupXmlPath -Encoding UTF8 -Force
    
  # ------------------------------------------------------------------
  # Generate bkupInfo.xml
  # ------------------------------------------------------------------
  $bkupInfoXml = @"
<?xml version="1.0" encoding="utf-8"?>
<BackupInst xmlns="http://www.microsoft.com/GroupPolicy/GPOOperations/Manifest">
  <GPOGuid>$gpoGuid</GPOGuid>
  <GPODomain>$($Script:TEMPLATE_DOMAIN)</GPODomain>
  <GPODomainGuid>$($Script:TEMPLATE_DOMAIN_GUID)</GPODomainGuid>
  <GPODomainController>$($Script:TEMPLATE_DC)</GPODomainController>
  <BackupTime>$generatedAt</BackupTime>
  <ID>$backupGuid</ID>
  <Comment><![CDATA[$GPODescription]]></Comment>
  <GPODisplayName><![CDATA[$GPOName]]></GPODisplayName>
</BackupInst>
"@
    
  $bkupInfoPath = Join-Path $gpoPath "bkupInfo.xml"
  $bkupInfoXml | Set-Content -Path $bkupInfoPath -Encoding UTF8 -Force
    
  # ------------------------------------------------------------------
  # Generate gpreport.xml
  # ------------------------------------------------------------------
  $rulesSummary = ($Rules | ForEach-Object { "CIS $($_.Rule.rule_id): $($_.Rule.title)" }) -join "`n      "
  $gpreportXml = @"
<?xml version="1.0" encoding="utf-8"?>
<GPO xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns="http://www.microsoft.com/GroupPolicy/Settings">
  <Identifier>
    <Id>$gpoGuid</Id>
    <Domain>$($Script:TEMPLATE_DOMAIN)</Domain>
  </Identifier>
  <Name>$GPOName</Name>
  <Description>$GPODescription

Rules Included ($($Rules.Count)):
      $rulesSummary
  </Description>
  <IncludeComments>true</IncludeComments>
  <CreatedTime>$generatedAt</CreatedTime>
  <ModifiedTime>$generatedAt</ModifiedTime>
  <ReadTime>${generatedAt}.000Z</ReadTime>
  <Computer>
    <VersionDirectory>1</VersionDirectory>
    <VersionSysvol>1</VersionSysvol>
    <Enabled>true</Enabled>
  </Computer>
  <User>
    <VersionDirectory>0</VersionDirectory>
    <VersionSysvol>0</VersionSysvol>
    <Enabled>true</Enabled>
  </User>
</GPO>
"@
    
  $gpreportPath = Join-Path $gpoPath "gpreport.xml"
  $gpreportXml | Set-Content -Path $gpreportPath -Encoding UTF8 -Force
    
  # ------------------------------------------------------------------
  # Generate manifest.xml at root level
  # ------------------------------------------------------------------
  $manifestXml = @"
<?xml version="1.0" encoding="utf-8"?>
<Backups xmlns="http://www.microsoft.com/GroupPolicy/GPOOperations/Manifest">
  <BackupInst>
    <GPOGuid>$gpoGuid</GPOGuid>
    <GPODomain>$($Script:TEMPLATE_DOMAIN)</GPODomain>
    <GPODomainGuid>$($Script:TEMPLATE_DOMAIN_GUID)</GPODomainGuid>
    <GPODomainController>$($Script:TEMPLATE_DC)</GPODomainController>
    <BackupTime>$generatedAt</BackupTime>
    <ID>$backupGuid</ID>
    <Comment><![CDATA[$GPODescription]]></Comment>
    <GPODisplayName><![CDATA[$GPOName]]></GPODisplayName>
  </BackupInst>
</Backups>
"@
    
  $manifestPath = Join-Path $OutputPath "manifest.xml"
  $manifestXml | Set-Content -Path $manifestPath -Encoding UTF8 -Force
    
  # ------------------------------------------------------------------
  # Generate Import-Policy.ps1 helper script
  # This script is included in the ZIP so end-users can run it directly
  # on their Domain Controller to import the GPO with zero configuration.
  # ------------------------------------------------------------------
  $rulesList = ($Rules | ForEach-Object { "#   - CIS $($_.Rule.rule_id): $($_.Rule.title)" }) -join "`n"
  $importScript = @"
#Requires -RunAsAdministrator
#Requires -Modules GroupPolicy
<#
.SYNOPSIS
    Imports the CIS Hardening GPO backup into your Active Directory environment.

.DESCRIPTION
    This script imports the pre-configured CIS Benchmark hardening policy
    into your domain as a new Group Policy Object.

    Generated: $generatedAt
    GPO Name:  $GPOName
    Rules:     $($Rules.Count)
$rulesList

.PARAMETER TargetName
    Name for the imported GPO. Defaults to '$GPOName'.

.PARAMETER Force
    Skip the confirmation prompt.

.EXAMPLE
    .\Import-Policy.ps1
    # Imports with default name, prompts for confirmation

.EXAMPLE
    .\Import-Policy.ps1 -TargetName "Production CIS Policy" -Force
    # Imports with custom name, no confirmation

.NOTES
    - Must be run on a Domain Controller or a machine with RSAT-GroupPolicy installed
    - Requires Domain Admin or equivalent GPO management permissions
    - The imported GPO is NOT linked to any OU by default - link it manually after review
#>
[CmdletBinding()]
param(
    [Parameter()]
    [string]`$TargetName = "$GPOName",

    [Parameter()]
    [switch]`$Force
)

`$ErrorActionPreference = "Stop"

# -- Pre-flight checks ---------------------------------------------
try {
    Import-Module GroupPolicy -ErrorAction Stop
} catch {
    Write-Error "GroupPolicy module not found. Install RSAT or run this on a Domain Controller."
    exit 1
}

# Resolve paths relative to this script's location
`$backupPath = `$PSScriptRoot
`$backupId   = "$backupGuid"

# -- Confirmation --------------------------------------------------
Write-Host ""
Write-Host "================================================================" -ForegroundColor Cyan
Write-Host "     CIS Hardening GPO Import Utility                           " -ForegroundColor Cyan
Write-Host "================================================================" -ForegroundColor Cyan
Write-Host ""
Write-Host "  Backup Path : `$backupPath"  -ForegroundColor Gray
Write-Host "  Backup ID   : `$backupId"    -ForegroundColor Gray
Write-Host "  Target GPO  : `$TargetName"  -ForegroundColor White
Write-Host "  Rules Count : $($Rules.Count)"          -ForegroundColor Gray
Write-Host ""

if (-not `$Force) {
    `$confirm = Read-Host "Import this GPO into your domain? (Y/N)"
    if (`$confirm -notin @('Y', 'y', 'Yes', 'yes')) {
        Write-Host "Import cancelled." -ForegroundColor Yellow
        exit 0
    }
}

# -- Import --------------------------------------------------------
Write-Host ""
Write-Host "[*] Importing GPO backup..." -ForegroundColor Cyan

try {
    `$result = Import-GPO ``
        -BackupId `$backupId ``
        -Path `$backupPath ``
        -TargetName `$TargetName ``
        -CreateIfNeeded

    Write-Host ""
    Write-Host "[+] GPO imported successfully!" -ForegroundColor Green
    Write-Host ""
    Write-Host "  GPO Name    : `$(`$result.DisplayName)" -ForegroundColor White
    Write-Host "  GPO ID      : `$(`$result.Id)"          -ForegroundColor Gray
    Write-Host "  Domain      : `$(`$result.DomainName)"  -ForegroundColor Gray
    Write-Host ""
    Write-Host "[!] IMPORTANT: The GPO is NOT linked to any OU yet." -ForegroundColor Yellow
    Write-Host "    Review the settings in GPMC, then link it to the appropriate OU." -ForegroundColor Yellow
    Write-Host ""
    Write-Host "    Example to link via PowerShell:" -ForegroundColor Gray
    Write-Host "    New-GPLink -Name '`$TargetName' -Target 'OU=Workstations,DC=yourdomain,DC=com'" -ForegroundColor DarkGray
    Write-Host ""
} catch {
    Write-Host ""
    Write-Host "[X] Import failed: `$(`$_.Exception.Message)" -ForegroundColor Red
    Write-Host ""
    Write-Host "    Common causes:" -ForegroundColor Yellow
    Write-Host "    - Not running as Domain Admin" -ForegroundColor Gray
    Write-Host "    - GroupPolicy module not available" -ForegroundColor Gray
    Write-Host "    - Backup folder structure is incomplete" -ForegroundColor Gray
    exit 1
}
"@

  $importScriptPath = Join-Path $OutputPath "Import-Policy.ps1"
  $importScript | Set-Content -Path $importScriptPath -Encoding UTF8 -Force

  # ------------------------------------------------------------------
  # Generate README.md
  # ------------------------------------------------------------------
  $readmeContent = @"
# CIS Windows Hardening GPO Backup

Generated: $(Get-Date -Format 'yyyy-MM-dd HH:mm:ss')
GPO Name: $GPOName
Rules Included: $($Rules.Count)

## Quick Start

### Option 1: Use the Import Script (Recommended)
``````powershell
# Run as Domain Admin on a Domain Controller or RSAT-enabled machine
.\Import-Policy.ps1
``````

### Option 2: Using Group Policy Management Console (GPMC)
1. Open Group Policy Management Console
2. Right-click on "Group Policy Objects"
3. Select "Import Settings..."
4. Browse to this folder
5. Select the backup to import

### Option 3: Manual PowerShell
``````powershell
Import-Module GroupPolicy
Import-GPO -BackupId "$backupGuid" -Path "<path-to-this-folder>" -TargetName "$GPOName" -CreateIfNeeded
``````

## Rules Included

$($Rules | ForEach-Object { "- CIS $($_.Rule.rule_id): $($_.Rule.title)" } | Out-String)

## Important Notes

- **Review before deployment** — Always verify settings in GPMC before linking
- **Test first** — Apply to a test OU with a few machines before organization-wide rollout
- **Not linked by default** — The imported GPO must be manually linked to target OUs
- **Portable** — Domain metadata in XML files are generic placeholders; Import-GPO handles remapping automatically
"@
    
  $readmePath = Join-Path $OutputPath "README.md"
  $readmeContent | Set-Content -Path $readmePath -Encoding UTF8 -Force
    
  return $OutputPath
}

function New-SecurityTemplateContent {
  [CmdletBinding()]
  param(
    [Parameter(Mandatory)]
    [array]$Rules
  )
    
  # Group rules by INF section
  $sections = @{}
    
  foreach ($ruleItem in $Rules) {
    $rule = $ruleItem.Rule
        
    if ($rule.implementation_gpo -and $rule.implementation_gpo.inf_section) {
      $section = $rule.implementation_gpo.inf_section
            
      if (-not $sections.ContainsKey($section)) {
        $sections[$section] = @()
      }
            
      $sections[$section] += @{
        RuleId = $rule.rule_id
        Title  = $rule.title
        Key    = $rule.implementation_gpo.inf_key
        Value  = $rule.implementation_gpo.inf_value
      }
    }
  }
    
  # Build INF content
  $inf = @"
[Unicode]
Unicode=yes

"@
    
  foreach ($section in $sections.Keys | Sort-Object) {
    $inf += "$section`r`n"
        
    foreach ($entry in $sections[$section]) {
      $inf += "; CIS $($entry.RuleId) - $($entry.Title)`r`n"
      $inf += "$($entry.Key) = $($entry.Value)`r`n"
    }
        
    $inf += "`r`n"
  }
    
  $inf += @"
[Version]
signature="`$CHICAGO`$"
Revision=1
"@
    
  return $inf
}

# Export functions
# Functions available when dot-sourced
