#Requires -Version 5.1
<#
.SYNOPSIS
    Report Generator for CIS Windows Hardening
.DESCRIPTION
    Generates HTML and JSON reports from hardening rule results.
#>

function New-HardeningReport {
    [CmdletBinding()]
    param(
        [Parameter(Mandatory)][array]$Rules,
        [Parameter(Mandatory)][string]$OutputPath,
        [Parameter()][array]$Results
    )
    
    $timestamp = Get-Date -Format 'yyyy-MM-dd HH:mm:ss'
    $hostname = $env:COMPUTERNAME
    $osVersion = (Get-CimInstance Win32_OperatingSystem).Caption
    
    $rulesSummary = $Rules | ForEach-Object {
        @{
            RuleId   = $_.Rule.rule_id
            Title    = $_.Rule.title
            Level    = $_.Rule.cis_level
            Category = $_.Rule.category
        }
    }
    
    $html = @"
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>CIS Windows Hardening Report</title>
    <style>
        :root { --pass: #00c853; --fail: #ff1744; --warn: #ff9100; --bg: #1a1a2e; --card: #16213e; --text: #eee; }
        * { box-sizing: border-box; margin: 0; padding: 0; }
        body { font-family: 'Segoe UI', sans-serif; background: var(--bg); color: var(--text); padding: 2rem; }
        .container { max-width: 1200px; margin: 0 auto; }
        header { text-align: center; margin-bottom: 2rem; }
        header h1 { font-size: 2rem; margin-bottom: 0.5rem; }
        .meta { color: #888; font-size: 0.9rem; }
        .dashboard { display: grid; grid-template-columns: repeat(auto-fit, minmax(200px, 1fr)); gap: 1rem; margin-bottom: 2rem; }
        .stat-card { background: var(--card); padding: 1.5rem; border-radius: 8px; text-align: center; }
        .stat-card .value { font-size: 2.5rem; font-weight: bold; }
        .stat-card .label { color: #888; margin-top: 0.5rem; }
        .stat-card.pass .value { color: var(--pass); }
        .stat-card.fail .value { color: var(--fail); }
        table { width: 100%; border-collapse: collapse; background: var(--card); border-radius: 8px; overflow: hidden; }
        th, td { padding: 1rem; text-align: left; border-bottom: 1px solid #333; }
        th { background: #0f3460; }
        tr:hover { background: #1f4068; }
        .badge { display: inline-block; padding: 0.25rem 0.75rem; border-radius: 4px; font-size: 0.8rem; }
        .badge-l1 { background: #4caf50; }
        .badge-l2 { background: #ff9800; }
        .section { margin-bottom: 2rem; }
        .section h2 { margin-bottom: 1rem; padding-bottom: 0.5rem; border-bottom: 2px solid #333; }
    </style>
</head>
<body>
    <div class="container">
        <header>
            <h1>CIS Windows Hardening Report</h1>
            <div class="meta">
                <span>Host: $hostname</span> | 
                <span>OS: $osVersion</span> | 
                <span>Generated: $timestamp</span>
            </div>
        </header>
        
        <div class="dashboard">
            <div class="stat-card">
                <div class="value">$($Rules.Count)</div>
                <div class="label">Total Rules</div>
            </div>
            <div class="stat-card">
                <div class="value">$(($Rules | Where-Object { $_.Rule.cis_level -eq 1 }).Count)</div>
                <div class="label">Level 1 Rules</div>
            </div>
            <div class="stat-card">
                <div class="value">$(($Rules | Where-Object { $_.Rule.cis_level -eq 2 }).Count)</div>
                <div class="label">Level 2 Rules</div>
            </div>
        </div>
        
        <div class="section">
            <h2>Rules Included</h2>
            <table>
                <thead>
                    <tr>
                        <th>Rule ID</th>
                        <th>Title</th>
                        <th>Level</th>
                        <th>Category</th>
                    </tr>
                </thead>
                <tbody>
"@
    
    foreach ($ruleItem in $Rules) {
        $rule = $ruleItem.Rule
        $levelBadge = if ($rule.cis_level -eq 1) { "badge-l1" } else { "badge-l2" }
        $html += @"
                    <tr>
                        <td><strong>$($rule.rule_id)</strong></td>
                        <td>$($rule.title)</td>
                        <td><span class="badge $levelBadge">L$($rule.cis_level)</span></td>
                        <td>$($rule.category)</td>
                    </tr>
"@
    }
    
    $html += @"
                </tbody>
            </table>
        </div>
        
        <footer style="text-align: center; margin-top: 2rem; color: #666; font-size: 0.9rem;">
            Generated by CIS Windows Hardening Generator v1.0
        </footer>
    </div>
</body>
</html>
"@
    
    $html | Set-Content -Path $OutputPath -Encoding UTF8 -Force
    
    # Also generate JSON
    $jsonPath = $OutputPath -replace '\.html$', '.json'
    $jsonReport = @{
        metadata = @{
            generated_at = $timestamp
            hostname     = $hostname
            os_version   = $osVersion
            total_rules  = $Rules.Count
        }
        rules    = $rulesSummary
    } | ConvertTo-Json -Depth 5
    
    $jsonReport | Set-Content -Path $jsonPath -Encoding UTF8 -Force
    
    return $OutputPath
}

# Function available when dot-sourced
